import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'researchResource',
  title: 'Research Resource',
  type: 'document',
  groups: [
    {name: 'basic', title: 'Basic', default: true},
    {name: 'evidence', title: 'Evidence & Method'},
    {name: 'files', title: 'Data & Downloads'},
    {name: 'meta', title: 'Metadata & Citation'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'basic',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'basic',
      options: {source: 'title', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'resourceType',
      title: 'Resource Type',
      type: 'string',
      group: 'basic',
      options: {
        list: [
          {title: 'Dataset', value: 'dataset'},
          {title: 'Methodology', value: 'methodology'},
          {title: 'Submission', value: 'submission'},
          {title: 'Research Brief', value: 'briefing'},
          {title: 'Report', value: 'report'},
          {title: 'Model / Calculator', value: 'model'},
          {title: 'Public Register', value: 'register'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'abstract',
      title: 'Abstract',
      type: 'text',
      rows: 5,
      group: 'basic',
      description: 'Neutral summary suitable for search results, journalists and citation indexes.',
      validation: (Rule) => Rule.required().max(600),
    }),
    defineField({
      name: 'authors',
      title: 'Authors / Contributors',
      type: 'array',
      group: 'meta',
      of: [{
        type: 'object',
        name: 'researchAuthor',
        fields: [
          {name: 'name', title: 'Name', type: 'string', validation: (Rule) => Rule.required()},
          {name: 'role', title: 'Role / affiliation', type: 'string'},
        ],
      }],
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published at',
      type: 'datetime',
      group: 'meta',
      description: 'Date this public research resource was first published on the Victorian website.',
      initialValue: () => new Date().toISOString(),
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'researchFirstDocumentedAt',
      title: 'Research first documented',
      type: 'datetime',
      group: 'meta',
      description: 'Earliest defensible date this research/evidence strand is documented in the policy corpus or its version history.',
    }),
    defineField({
      name: 'researchProvenance',
      title: 'Research provenance',
      type: 'string',
      group: 'meta',
      description: 'Short provenance note, such as the omnibus file and Git commit where the research first appears.',
    }),
    defineField({
      name: 'version',
      title: 'Version',
      type: 'string',
      group: 'meta',
      description: 'e.g. 1.0, 2026-09 release',
    }),
    defineField({
      name: 'geographicCoverage',
      title: 'Geographic Coverage',
      type: 'string',
      group: 'meta',
      initialValue: 'Victoria, Australia',
    }),
    defineField({
      name: 'license',
      title: 'Licence',
      type: 'string',
      group: 'meta',
      options: {
        list: [
          {title: 'CC BY 4.0', value: 'CC-BY-4.0'},
          {title: 'CC BY-SA 4.0', value: 'CC-BY-SA-4.0'},
          {title: 'CC0 / Public Domain Dedication', value: 'CC0-1.0'},
          {title: 'All rights reserved', value: 'all-rights-reserved'},
          {title: 'Other', value: 'other'},
        ],
      },
      initialValue: 'CC-BY-4.0',
    }),
    defineField({
      name: 'keyFindings',
      title: 'Key Findings',
      type: 'array',
      group: 'basic',
      description: 'Three to six concise findings for journalists, candidates, search snippets and AI retrieval. These should be factual conclusions, not slogans.',
      of: [{type: 'string'}],
      validation: (Rule) => Rule.max(6),
    }),
    defineField({
      name: 'tags',
      title: 'Topics',
      type: 'array',
      group: 'basic',
      of: [{type: 'string'}],
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'methodology',
      title: 'Methodology',
      type: 'array',
      group: 'evidence',
      of: [{type: 'block'}],
    }),
    defineField({
      name: 'limitations',
      title: 'Limitations',
      type: 'array',
      group: 'evidence',
      description: 'Known caveats, uncertainty and what the resource should not be used to conclude.',
      of: [{type: 'block'}],
    }),
    defineField({
      name: 'body',
      title: 'Resource Body',
      type: 'array',
      group: 'evidence',
      of: [
        {
          type: 'block',
          marks: {
            annotations: [{
              name: 'link',
              type: 'object',
              title: 'Link',
              fields: [{name: 'href', type: 'url', title: 'URL'}],
            }],
          },
        },
        {
          type: 'image',
          options: {hotspot: true},
          fields: [{name: 'alt', type: 'string', title: 'Alternative text'}],
        },
      ],
    }),
    defineField({
      name: 'sources',
      title: 'Sources',
      type: 'array',
      group: 'evidence',
      of: [{
        type: 'object',
        name: 'researchSource',
        fields: [
          {name: 'title', title: 'Source title', type: 'string', validation: (Rule) => Rule.required()},
          {name: 'publisher', title: 'Publisher / institution', type: 'string'},
          {name: 'url', title: 'URL', type: 'url', validation: (Rule) => Rule.required()},
          {name: 'publishedAt', title: 'Source date', type: 'date'},
          {name: 'accessedAt', title: 'Accessed date', type: 'date'},
          {name: 'note', title: 'How it is used', type: 'text', rows: 2},
        ],
      }],
    }),
    defineField({
      name: 'downloads',
      title: 'Downloads / Data',
      type: 'array',
      group: 'files',
      of: [{
        type: 'object',
        name: 'researchDownload',
        fields: [
          {name: 'label', title: 'Label', type: 'string', validation: (Rule) => Rule.required()},
          {name: 'format', title: 'Format', type: 'string', description: 'CSV, JSON, PDF, XLSX, GeoJSON, etc.'},
          {name: 'url', title: 'External URL', type: 'url'},
          {name: 'file', title: 'Uploaded file', type: 'file'},
          {name: 'description', title: 'Description', type: 'text', rows: 2},
        ],
      }],
    }),
    defineField({
      name: 'externalProjectUrl',
      title: 'External Project / Interactive Tool',
      type: 'url',
      group: 'files',
      description: 'Optional canonical interactive tool, dashboard or repository associated with this resource.',
    }),
    defineField({
      name: 'repositoryUrl',
      title: 'Source Repository',
      type: 'url',
      group: 'files',
    }),
    defineField({
      name: 'relatedPolicies',
      title: 'Related Policies',
      type: 'array',
      group: 'meta',
      of: [{type: 'reference', to: [{type: 'policy'}]}],
    }),
    defineField({
      name: 'citationTitle',
      title: 'Citation Title Override',
      type: 'string',
      group: 'meta',
      description: 'Normally leave blank; defaults to the resource title.',
    }),
    defineField({
      name: 'doi',
      title: 'DOI / Persistent Identifier',
      type: 'string',
      group: 'meta',
      description: 'Optional. Use if a resource is deposited with a repository that issues a DOI.',
    }),
    defineField({
      name: 'featured',
      title: 'Featured Resource',
      type: 'boolean',
      group: 'basic',
      initialValue: false,
    }),
  ],
  preview: {
    select: {title: 'title', type: 'resourceType', date: 'publishedAt'},
    prepare({title, type, date}) {
      return {title, subtitle: [type, date ? new Date(date).toLocaleDateString() : null].filter(Boolean).join(' • ')}
    },
  },
  orderings: [
    {title: 'Published Date, New', name: 'publishedDesc', by: [{field: 'publishedAt', direction: 'desc'}]},
    {title: 'Title, A-Z', name: 'titleAsc', by: [{field: 'title', direction: 'asc'}]},
  ],
})
